spring:
  application:
    name: config-server
  profiles:
    active: native  
  rabbitmq:
    host: 192.168.153.131
    port: 5672
    username: admin
    password: admin   
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config #向本地拉取配置信息
#        git:
#          uri: https://github.com/zhuzhihan/sp-config
#          search-paths: 
#          - config
          #私有库需要加用户名和密码
#          username: zhuzhihan
#          password: z2209215377
    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh